dist: trusty

language: 'node_js'

node_js:
  - '10'

# if: type IN (cron, pull_request)

before_install:
  - 'if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then bash .travis/cron-setup.sh; fi'

before_script:
  - npm ci

script:
  - node update.js --all

